### ISSUE TITLE
Implement the profile page

### ISSUE THREAD

**Issue by GabrielPedroza** [upe-webdev-2/codeclash-frontend#32]
https://www.figma.com/file/hogMpfKqVahUtawBcINfj4/Codeclash?node-id=0%3A1

**Comment by Mikeatron-User** [comment]
**Update 1**
I created the initial leaderboard prototype. I used mock data to fill the leaderboard. I then applied styling using Tailwind CSS.
There are some things I need to adjust about it, but otherwise, great progress was made so far.
![image](https://user-images.githubusercontent.com/70152741/202828703-61b00547-e490-446c-8a93-91f873fdb125.png)
